spring:
  application:
    name: api-event
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
  data:
    mongodb:
      uri: mongodb+srv://group3-PI2:fI21lcFyH4LlsT5M@cluster-pi2.uqv6omj.mongodb.net/MasterEvents
      database: MasterEvents




