spring:
  application:
    name: api-company
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
  datasource:
    #    --> DB Cloud
    url: jdbc:mysql://db.ctd.academy:3306/pi21023c02_GRUPO3
    username: pi21023c02_GRUPO3
    password: oof2Eile
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    --> DB Local
    #    url: jdbc:mysql://localhost:3306/EMarket
    #    username: root
    #    password: T15F1542

  jpa:
    hibernate:
      ddl-auto: update
