spring:
  application:
    name: api-company
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/EMarket
    username: root
    password: T15F1542
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
