server:
  port: 8761
spring:
  application:
    name: api-eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceURL:
      defaultZone: http://localhost:8761/eureka